### ISSUE TITLE
Missing credits image

### ISSUE THREAD

**Issue by chrzyki** [clld/sails#5]
This image is no longer available. If there is anything else that you'd like to see instead just let me know!

https://github.com/clld/sails/blob/09f20033a02d452c5460320111f473c3ded35adf/sails/templates/dataset/detail_html.mako#L162-L164

**Comment by chrzyki** [comment]
@d97hah Would you like to see a different image here?

**Comment by d97hah** [comment]
Hi Christoph! Sorry I missed, this. Yes, this logo:
https://www.ru.nl/publish/pages/729142/ru_nl_a4_rgb_2017_lustum95.jpg

Pada tanggal Jum, 7 Sep 2018 pukul 12.17 Christoph Rzymski <
notifications@github.com> menulis:

**Comment by chrzyki** [comment]
No worries & thanks. Fixed. :)
